import type { Meal, RawMeal } from "../types/meal";

export function mapMeal(raw: RawMeal): Meal {
  return {
  id: raw.id ?? raw._id ?? "",
  name: raw.name ?? raw.title ?? "Untitled meal",
  description: raw.description ?? "",
  price: Number(raw.price ?? 0),
  imageUrl: raw.imageUrl ?? raw.image ?? "",
  category: raw.category ?? "Other",
  area: "",
  instructions: "",
  image: "",
  idMeal: "",
  strMeal: "",
  strMealAlternate: null,
  strCategory: null,
  strArea: null,
  strCountry: null,
  strInstructions: "",
  strMealThumb: null,
  strTags: null,
  strYoutube: "",
  strIngredient1: "",
  strIngredient2: "",
  strIngredient3: "",
  strIngredient4: "",
  strIngredient5: "",
  strIngredient6: "",
  strIngredient7: "",
  strIngredient8: "",
  strIngredient9: "",
  strIngredient10: "",
  strIngredient11: "",
  strIngredient12: "",
  strIngredient13: "",
  strIngredient14: "",
  strIngredient15: "",
  strIngredient16: "",
  strIngredient17: "",
  strIngredient18: "",
  strIngredient19: "",
  strIngredient20: "",
  strMeasure1: "",
  strMeasure2: "",
  strMeasure3: "",
  strMeasure4: "",
  strMeasure5: "",
  strMeasure6: "",
  strMeasure7: "",
  strMeasure8: "",
  strMeasure9: "",
  strMeasure10: "",
  strMeasure11: "",
  strMeasure12: "",
  strMeasure13: "",
  strMeasure14: "",
  strMeasure15: "",
  strMeasure16: "",
  strMeasure17: "",
  strMeasure18: "",
  strMeasure19: "",
  strMeasure20: "",
  strSource: null,
  strImageSource: null,
  strCreativeCommonsConfirmed: null,
  dateModified: null
};
}

export function mapMealsList(rawList: RawMeal[] | null | undefined): Meal[] {
  return (rawList ?? []).map(mapMeal);
}
